version: '3'
services:
  house-management:
    build: ./HouseManagement
    container_name: house-management
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_HTTP_PORTS=80

volumes:
  keys: