version: '3'
services:
  house-management:
    build: ./HouseManagement
    container_name: house-management
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    env_file:
      - ../config.yml
    depends_on:
      - postgres

  postgres:
    container_name: postgres-db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
      - TZ="Asia/Ho_Chi_Minh"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  keys:
  postgres: