version: '3'
services:
  house-management:
    build: ./HouseManagement
    container_name: house-management
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - keys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_HTTP_PORTS=80
    env_file:
      - ../config.yml
    depends_on:
      - postgres

  postgres:
    container_name: postgres-db
    image: postgres
    config:
      timezone: "Asia/Ho_Chi_Minh"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Abcd@1234}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  keys:
  postgres: