version: '3'
services:
  motel-dotnet:
    build: ./HouseManagement
    container_name: motel-dotnet
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      - ASPNETCORE_URLS=http://+

volumes:
  keys: